apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springdemo
    app.kubernetes.io/component: springdemo
    app.kubernetes.io/instance: springdemo
  name: springdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: springdemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: springdemo
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: springdemo
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: springdemo
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: springdemo
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: springdemo
          image: quay.io/prashanthsriram/springdemo@sha256:02a6715213c89811fc37803fdd65083c616d91e78fde6ee67446a86671e4708f
          imagePullPolicy: IfNotPresent
          name: springdemo
          ports:
            - containerPort: 8080
              protocol: TCP
