apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-11-14T14:08:09Z"
  labels:
    app: springdemo
    app.kubernetes.io/component: springdemo
    app.kubernetes.io/instance: springdemo
  name: springdemo
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: springdemo
  sessionAffinity: None
  type: ClusterIP
