apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  username: {{ .Values.configmap.username }}
  SPRING_DATASOURCE_URL: {{ .Values.configmap.spring_datasource_url }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.configmap.spring_datasource_username }}